### ISSUE TITLE
Missing GPG key

### ISSUE THREAD

**Issue by polarbub** [RootHide/roothide.github.io#3]
The `procursus` repo is [signed](https://github.com/roothide/roothide.github.io/blob/main/procursus/dists/iphoneos-arm64e/1900/Release.gpg) with GPG, but I can't find where the public key is. [This](https://github.com/roothide/roothide.github.io/tree/main/procursus/pool/main/iphoneos-arm64e/1900/keyring) package is labeled as the keyring, but it doesn't seem to have the same key. I think that the fingerprint of the signed repo is `664421BE84375685` and the one in the package is `6430292CF9551B0E`. Any ideas where I can get the right key?

**Comment by roothider** [comment]
this repository is running a custom fork of procursus, which does not have GPG signatures and keys set up.
